# Generated by Django 5.1 on 2024-08-14 07:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojoconf', '0001_initial'),
        ('shodan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='i.e "Shimpads, Training material"', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='i.e "Adult, Children, Family"', max_length=200)),
                ('frequency', models.CharField(help_text='i.e "Weekly"', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Subscription, Category or Event is required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.category')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
                ('event', models.ForeignKey(blank=True, help_text='Subscription, Category or Event is required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shodan.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.student')),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription, Category or Event is required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.subscription')),
            ],
        ),
    ]
