# Generated by Django 5.1 on 2024-08-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_category_sales'),
        ('shodan', '0015_alter_session_classes_alter_session_event_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
