# Generated by Django 5.1 on 2024-08-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0004_event'),
        ('financial', '0002_sale_date_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional, if related with an event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dojoconf.event'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Subscription, Category or Event is required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dojoconf.event'),
        ),
    ]
