# Generated by Django 5.1 on 2024-08-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0001_initial'),
        ('financial', '0003_rename_sales_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
    ]
