# Generated by Django 5.1 on 2024-08-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_rename_subscription_subscriptionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCustomFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], help_text='i.e "Monthly, Quarterly, Custom (i.e School Term)"', max_length=200),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='custom_frequencies',
            field=models.ManyToManyField(blank=True, to='financial.subscriptioncustomfrequency'),
        ),
    ]
