# Generated by Django 5.1 on 2024-08-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_subscriptioncustomfrequency_dojo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='custom_frequencies',
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='custom_frequencies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.subscriptioncustomfrequency'),
        ),
    ]
