# Generated by Django 5.1 on 2024-08-20 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_remove_subscriptionproduct_custom_frequencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='custom_frequencies',
        ),
        migrations.AddField(
            model_name='subscriptioncustomfrequency',
            name='subscription_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.subscriptionproduct'),
        ),
    ]
