# Generated by Django 5.1 on 2024-08-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_alter_subscriptioncustomfrequency_subscription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncustomfrequency',
            name='frequency',
            field=models.TextField(help_text="\n    Each row is a date. You can add ranges (i.e '2024-08-01 to 2024-08-30' or single days (i.e 2024-08-01))\n    \n    For example, to create a subscription that will cover 4 payments, one per school holidays in 2024 in SA, \n    those will be the contents:\n    2024-01-29 to 2024-04-12 \n    2024-04-29 to 2024-07-05\n    2024-07-22 to 2024-09-27\n    2024-10-14 to 2024-12-13\n    "),
        ),
    ]
