# Generated by Django 5.1 on 2024-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_alter_subscriptioncustomfrequency_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD')], default='AUD', max_length=200),
        ),
    ]
