# Generated by Django 5.1 on 2024-08-20 06:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0006_dojo_hostname'),
        ('financial', '0012_subscriptionproduct_amount_and_more'),
        ('shodan', '0014_alter_attendance_duration_alter_attendance_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD')], default='AUD', max_length=3),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('cancelled', 'CANCELLED')], default='active', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Auto populated if empty', max_digits=6)),
                ('currency', models.CharField(choices=[('AUD', 'AUD')], default='AUD', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.student')),
                ('subscription_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.subscriptionproduct')),
            ],
        ),
    ]
