# Generated by Django 5.1 on 2024-08-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_alter_subscriptionproduct_currency_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto populated if empty', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD')], default='AUD', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_from',
            field=models.DateField(blank=True, help_text='Auto populated if type is subscription and it is empty', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_to',
            field=models.DateField(blank=True, help_text='Auto populated if type is subscription and it is empty', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription, Category or Event is required.', null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto populated if empty', max_digits=6, null=True),
        ),
    ]
