# Generated by Django 5.1 on 2024-08-21 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_sale_amount_sale_currency_sale_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional, if related with a category.', null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD')], default='AUD', max_length=3),
        ),
    ]
