# Generated by Django 5.1 on 2024-09-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0007_alter_address_latitude_alter_address_longitude'),
        ('financial', '0016_rename_subscriptionproduct_membershipproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionCustomFrequency',
            new_name='MembershipCustomFrequency',
        ),
    ]
