# Generated by Django 5.1 on 2024-09-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0007_alter_address_latitude_alter_address_longitude'),
        ('financial', '0017_rename_subscriptioncustomfrequency_membershipcustomfrequency'),
        ('shodan', '0014_alter_attendance_duration_alter_attendance_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Membership',
        ),
    ]
