# Generated by Django 5.1 on 2024-09-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_rename_subscription_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='subscription_product',
            new_name='membership_product',
        ),
        migrations.RemoveField(
            model_name='membershipcustomfrequency',
            name='subscription_product',
        ),
    ]
