# Generated by Django 5.1 on 2024-09-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_remove_sale_subscription_sale_membership_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipCustomFrequency',
        ),
    ]
