# Generated by Django 5.1 on 2024-09-04 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0007_alter_address_latitude_alter_address_longitude'),
        ('financial', '0021_delete_membershipcustomfrequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCustomFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.TextField(help_text="\n    Each row is a date. You can add ranges (i.e '2024-08-01 to 2024-08-30' or single days (i.e 2024-08-01))<br>\n    <br>\n    For example, to create a membership that will cover 4 payments, one per school holidays in 2024 in SA,\n    those will be the contents:<br>\n    2024-01-29 to 2024-04-12<br>\n    2024-04-29 to 2024-07-05<br>\n    2024-07-22 to 2024-09-27<br>\n    2024-10-14 to 2024-12-13<br>\n    ")),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
                ('membership_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.membershipproduct')),
            ],
        ),
    ]
