# Generated by Django 5.1 on 2024-08-14 23:40

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=''),
            preserve_default=False,
        ),
    ]
