# Generated by Django 5.1 on 2024-08-15 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0002_dojo_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='users',
            field=models.ManyToManyField(related_name='dojos', to=settings.AUTH_USER_MODEL),
        ),
    ]
