# Generated by Django 5.1 on 2024-08-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_to',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='i.e "Seminar, Grading, Competition, etc."', max_length=200),
        ),
    ]
