# Generated by Django 5.1 on 2024-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0005_remove_event_date_remove_event_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='hostname',
            field=models.CharField(blank=True, help_text='Hosted hostname (i.e dojo.brightonkarate.com.au)', max_length=255, null=True),
        ),
    ]
