# Generated by Django 5.1 on 2024-08-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0006_dojo_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text="<a target='_blank' href='https://www.latlong.net/'>Find Latitude</a>", max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text="<a target='_blank' href='https://www.latlong.net/'>Find Longitude</a>", max_digits=20, null=True),
        ),
    ]
