# Generated by Django 5.1 on 2024-09-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0007_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojo',
            options={'verbose_name': 'Class Interval', 'verbose_name_plural': 'Class Intervals'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={},
        ),
        migrations.RemoveField(
            model_name='classes',
            name='interval',
        ),
        migrations.AddField(
            model_name='interval',
            name='classes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojoconf.classes'),
        ),
    ]
