# Generated by Django 5.1 on 2024-09-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0008_alter_dojo_options_alter_interval_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='updated_at',
        ),
    ]
