# Generated by Django 5.1 on 2026-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0010_alter_dojo_options_classes_days_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_waiver',
            field=models.BooleanField(default=False, help_text='If enabled, an "Events" button appears on the landing page linking to the waiver form.'),
        ),
    ]
