# Generated by Django 5.1 on 2026-06-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0011_event_requires_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waiver_success_message',
            field=models.TextField(blank=True, help_text='Custom message shown on the waiver success page after submission. Leave blank for default message.', null=True),
        ),
    ]
