# Generated by Django 5.1 on 2026-06-14 03:04

import dojoconf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0012_event_waiver_success_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='kiosk_pin',
            field=models.CharField(blank=True, help_text='4-6 digit PIN for activating Kiosk Mode on the student-facing landing page.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='dojo',
            name='logo',
            field=models.FileField(blank=True, help_text='Dojo logo (transparent PNG designed for white background). Displayed on all public pages.', null=True, storage=dojoconf.models.get_file_storage, upload_to=dojoconf.models._create_dojo_logo_path),
        ),
    ]
