# Generated by Django 5.1 on 2026-06-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0013_dojo_kiosk_pin_dojo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='kiosk_failed_attempts',
            field=models.IntegerField(default=0, help_text='Consecutive failed kiosk PIN attempts. Resets on success or admin unlock.'),
        ),
        migrations.AddField(
            model_name='dojo',
            name='kiosk_locked',
            field=models.BooleanField(default=False, help_text='When True, all kiosk PIN entry is blocked. Admin must unlock.'),
        ),
    ]
