# Generated by Django 5.2.15 on 2026-06-14 06:02

import dojoconf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0015_alter_address_created_at_alter_classes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='logo',
            field=models.FileField(blank=True, help_text='Dojo logo (transparent PNG designed for white background). Displayed on all public pages.', null=True, storage=dojoconf.models.get_public_file_storage, upload_to=dojoconf.models._create_dojo_logo_path),
        ),
    ]
