# Generated by Django 5.2.15 on 2026-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0016_alter_dojo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='External URL to the dojo privacy policy page. Shown as a "Privacy Policy" link in the public site footer when set.', max_length=500, null=True),
        ),
    ]
