# Generated by Django 5.1 on 2024-08-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(blank=True, help_text='For standard classes will be calculated automatically if empty', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_from',
            field=models.TimeField(blank=True, help_text='For standard classes will be calculated automatically if empty', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='time_to',
            field=models.TimeField(blank=True, help_text='For standard classes will be calculated automatically if empty', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. Autogenerated if empty. i.e "Adults Monday Session" or "Oct 2024 Seminar"', max_length=200, null=True),
        ),
    ]
