# Generated by Django 5.1 on 2024-08-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0002_rename_dojo_dojomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DojoModel',
            new_name='Dojo',
        ),
    ]
