# Generated by Django 5.1 on 2024-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0002_session_duration_session_time_from_session_time_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='minutes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, help_text='Optional, it will be calculated automatically if empty (i.e 1:30 for 90 minutes)', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='points',
            field=models.IntegerField(blank=True, help_text='Optional, if it adds points towards the next grading.', null=True),
        ),
    ]
