# Generated by Django 5.1 on 2024-08-13 04:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0003_rename_dojomodel_dojo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('kyu', models.IntegerField()),
                ('dan', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.dojo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.studentstatus')),
            ],
        ),
    ]
