# Generated by Django 5.1 on 2024-08-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0003_remove_attendance_minutes_attendance_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, help_text='It will be populated automatically if empty', null=True),
        ),
    ]
