# Generated by Django 5.1 on 2024-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0004_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2024-08-14'),
            preserve_default=False,
        ),
    ]
