# Generated by Django 5.1 on 2024-08-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0004_studentstatus_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='kyu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
