# Generated by Django 5.1 on 2024-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0005_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, help_text='It will be calculated automatically if empty', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_from',
            field=models.TimeField(default='16:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time_to',
            field=models.TimeField(default='20:30'),
            preserve_default=False,
        ),
    ]
