# Generated by Django 5.1 on 2024-08-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0005_alter_student_dan_alter_student_kyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dojo',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
