# Generated by Django 5.1 on 2024-08-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0004_event'),
        ('financial', '0003_alter_expense_event_alter_sale_event'),
        ('shodan', '0006_event_duration_event_time_from_event_time_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event or Classes needs to be defined', null=True, on_delete=django.db.models.deletion.CASCADE, to='dojoconf.event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
