# Generated by Django 5.1 on 2024-08-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0007_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='data',
            field=models.CharField(default='', help_text='i.e "Monday"', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interval',
            name='name',
            field=models.CharField(help_text='i.e "Every Monday"', max_length=200),
        ),
        migrations.AlterField(
            model_name='interval',
            name='type',
            field=models.CharField(help_text='i.e "Weekly"', max_length=200),
        ),
    ]
