# Generated by Django 5.1 on 2024-08-13 05:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0008_interval_data_alter_interval_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'verbose_name': 'Class Interval', 'verbose_name_plural': 'Class Intervals'},
        ),
        migrations.AddField(
            model_name='interval',
            name='dojo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shodan.dojo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name', max_length=200)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.dojo')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='i.e "Adults"', max_length=200)),
                ('time_from', models.TimeField(help_text='i.e "Starting Local Time"')),
                ('time_to', models.TimeField(help_text='i.e "Finishing Local Time"')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.address')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.dojo')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.interval')),
            ],
        ),
    ]
