# Generated by Django 5.1 on 2024-08-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0009_alter_interval_options_interval_dojo_address_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
