# Generated by Django 5.1 on 2024-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0009_alter_student_hours_alter_student_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.IntegerField(default=0, help_text='Total student training time (in minutes).'),
        ),
    ]
