# Generated by Django 5.1 on 2024-08-13 05:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0010_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='i.e "Adults"', max_length=200)),
                ('time_from', models.TimeField(help_text='i.e "Starting Local Time"')),
                ('time_to', models.TimeField(help_text='i.e "Finishing Local Time"')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.address')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.dojo')),
            ],
        ),
    ]
