# Generated by Django 5.1 on 2024-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0010_alter_student_hours'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='attendance',
        #     name='duration',
        #     field=models.DurationField(blank=True, default=0, help_text='Optional, it will be calculated automatically if empty (i.e 1:30 for 90 minutes)'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='attendance',
            name='points',
            field=models.IntegerField(blank=True, default=0, help_text='Optional, if it adds points towards the next grading.'),
            preserve_default=False,
        ),
    ]
