# Generated by Django 5.1 on 2024-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0011_alter_attendance_duration_alter_attendance_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.IntegerField(blank=True, default=0, help_text='Total student training time (in minutes).'),
        ),
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
