# Generated by Django 5.1 on 2024-08-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0011_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time_to',
        ),
    ]
