# Generated by Django 5.1 on 2024-08-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0012_remove_events_time_from_remove_events_time_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
