# Generated by Django 5.1 on 2024-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0012_alter_student_hours_alter_student_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, help_text='Optional, it will be calculated automatically if empty (i.e 1:30 for 90 minutes)'),
        ),
    ]
