# Generated by Django 5.1 on 2024-08-13 05:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0014_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='classes',
            field=models.ForeignKey(blank=True, help_text='Event or Classes needs to be defined', null=True, on_delete=django.db.models.deletion.CASCADE, to='shodan.classes'),
        ),
        migrations.AlterField(
            model_name='session',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event or Classes needs to be defined', null=True, on_delete=django.db.models.deletion.CASCADE, to='shodan.event'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.dojo')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.student')),
            ],
        ),
    ]
