# Generated by Django 5.1 on 2024-08-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0001_initial'),
        ('financial', '0004_alter_category_dojo_alter_sale_dojo_and_more'),
        ('shodan', '0015_alter_session_classes_alter_session_event_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.address'),
        ),
        migrations.RemoveField(
            model_name='classes',
            name='address',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='dojo',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='interval',
        ),
        migrations.AlterField(
            model_name='session',
            name='classes',
            field=models.ForeignKey(blank=True, help_text='Event or Classes needs to be defined', null=True, on_delete=django.db.models.deletion.CASCADE, to='dojoconf.classes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
        migrations.RemoveField(
            model_name='interval',
            name='dojo',
        ),
        migrations.AlterField(
            model_name='session',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.studentstatus'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
        migrations.DeleteModel(
            name='Dojo',
        ),
        migrations.DeleteModel(
            name='StudentStatus',
        ),
    ]
