# Generated by Django 5.1 on 2024-09-05 04:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0015_studentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='students/%(dojo_id)/%(student_id)'),
        ),
    ]
