# Generated by Django 5.1 on 2024-09-10 07:18

import shodan.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0016_remove_studentdocument_uploaded_at_student_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=shodan.models._create_student_document_path),
        ),
    ]
