# Generated by Django 5.1 on 2024-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0019_student_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start',
            field=models.DateField(blank=True, help_text='Student Start Date.', null=True),
        ),
    ]
