# Generated by Django 5.1 on 2024-09-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0020_alter_student_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
