# Generated by Django 5.1 on 2026-06-14 01:47

import shodan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0022_eventwaiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventwaiver',
            name='applicant_signature',
            field=models.FileField(help_text='Applicant signature image (PNG).', storage=shodan.models.get_file_storage, upload_to=shodan.models._create_waiver_signature_path),
        ),
        migrations.AlterField(
            model_name='eventwaiver',
            name='guardian_signature',
            field=models.FileField(blank=True, help_text='Guardian signature image (PNG). Required if applicant is under 18.', null=True, storage=shodan.models.get_file_storage, upload_to=shodan.models._create_waiver_signature_path),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(storage=shodan.models.get_file_storage, upload_to=shodan.models._create_student_document_path),
        ),
    ]
