# Generated by Django 5.1 on 2026-06-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0023_alter_eventwaiver_applicant_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwaiver',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
