# Generated by Django 5.1 on 2026-06-14 03:04

import datetime
import django.db.models.deletion
import shodan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0013_dojo_kiosk_pin_dojo_logo'),
        ('shodan', '0024_eventwaiver_emergency_contact_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_grade', models.CharField(blank=True, help_text='Current grade (Kyu)', max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(max_length=50)),
                ('terms_accepted', models.BooleanField(default=False, help_text='Participant agrees to the terms and conditions.')),
                ('questionnaire_responses', models.JSONField(default=dict, help_text='Physical readiness questionnaire responses: {"q1": "yes", "q2": "no", ...}')),
                ('medical_specify', models.TextField(blank=True, help_text='Q13: Please specify any illness not mentioned.', null=True)),
                ('other_reason_specify', models.TextField(blank=True, help_text='Q14: Please specify any other reason.', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Allergies details.', null=True)),
                ('applicant_signature', models.FileField(help_text='Applicant signature image (PNG).', storage=shodan.models.get_file_storage, upload_to=shodan.models._create_student_waiver_signature_path)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_date', models.DateField()),
                ('guardian_signature', models.FileField(blank=True, help_text='Guardian signature image (PNG). Required if applicant is under 18.', null=True, storage=shodan.models.get_file_storage, upload_to=shodan.models._create_student_waiver_signature_path)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shodan.student')),
            ],
        ),
    ]
