# Generated by Django 5.2.15 on 2026-07-14 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoconf', '0017_dojo_privacy_policy_url'),
        ('shodan', '0026_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedbackLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Random URL-safe token. Auto-generated on creation.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='When False, the feedback form is closed.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_link', to='shodan.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict, help_text='Anonymous feedback responses: {question_pk: answer_string}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojoconf.dojo')),
                ('feedback_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='shodan.sessionfeedbacklink')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-5)'), ('yes_no', 'Yes/No'), ('text', 'Open Text'), ('choice', 'Dropdown Choice')], max_length=10)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of strings for dropdown options. Used only when question_type is "choice".')),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='shodan.sessionfeedbacklink')),
            ],
        ),
    ]
