# Generated by Django 5.2.15 on 2026-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0027_session_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='honeypot_value',
            field=models.CharField(blank=True, default='', help_text='The captured honeypot (email2) value. Populated only on bot submissions.', max_length=500),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP captured once on first submission, for abuse/spam detection.', null=True),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='True when the honeypot field was filled (suspected bot submission).'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='Browser user-agent captured once on first submission, for abuse/spam detection.'),
        ),
    ]
