# Generated by Django 5.2.15 on 2026-07-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodan', '0028_feedback_abuse_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedbackquestion',
            name='conditional_answer',
            field=models.CharField(blank=True, default='', help_text='The parent answer value that makes this question visible (e.g. "yes" or "no").', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionfeedbackquestion',
            name='conditional_parent',
            field=models.ForeignKey(blank=True, help_text='When set, this question is only shown if the parent question is answered with the value in "Conditional answer".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_children', to='shodan.sessionfeedbackquestion'),
        ),
    ]
